name: 'Cached Install'
description: 'Sets up node and installs cached dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: Cache Modules
      id: npm-cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      shell: bash
      if: ${{ !steps.npm-cache.outputs.cache-hit }}
      run: npm ci
