name: Notifier

on:
  push:
    branches: [main]

jobs:
  messageSlack:
    runs-on: ubuntu-latest
    steps:
      - name: Notification Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github
          SLACK_TITLE: Frontend
          SLACK_USERNAME: BotRepo
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: '¡Frontend has been updated!'
on:
  pull_request:
    types: [opened]
    branches: [main, dev]
jobs:
  messageSlack:
    runs-on: ubuntu-latest
    steps:
      - name: Notification Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github
          SLACK_TITLE: Frontend
          SLACK_USERNAME: BotRepo
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: '¡Frontend has another PR!'    
